---
title: "Краш-тест для диалектологической анкеты"
author: "А. Федоренко, Г. Мороз"
date: "15 мая 2018"
output: slidy_presentation
knit: (function(inputFile, encoding) { 
      out_dir <- 'docs';
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=file.path(dirname(inputFile), out_dir, 'index.html')) })
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(lingtypology)
library(dplyr)
```

## Trip details
```{r}
df <- readxl::read_xlsx("villages.xlsx")
circassian %>% 
  filter(district == "ra") ->
  cir

map.feature(language = df$language,
            features = df$dialect,
            label = df$village,
            label.hide = FALSE,
            longitude = df$longitude,
            latitude = df$latitude,
            tile = "none") %>% 
map.feature(cir$language,
            longitude = cir$longitude,
            latitude = cir$latitude,
            opacity = 0.2,
            tile = "Esri.WorldGrayCanvas",
            pipe.data = .,
            zoom.level = 9,
            color = "red")
```


